# -*- coding: utf-8 -*-
"""rssi_QML_VQC_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16eC-kMAmssby-8WYOuZZTPAzb3FQMv_t
"""

#1. Install dependencies
!pip install pennylane pennylane-qiskit pandas scikit-learn
#!pip install ...

#Mount Google Drive in Colab
from google.colab import drive
drive.mount('/content/drive')

# Then the path will be:

"/content/drive/My Drive/Datasets_QML/rssiML.csv"

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score

import pennylane as qml

# -----------------------------
# 1. Load and prepare the data
# -----------------------------
#CSV_FILE = "rssiML (1).csv"
#df = pd.read_csv(CSV_FILE)
df = pd.read_csv("/content/drive/My Drive/Datasets_QML/rssiML.csv")

# Features: A, B, C, D
X = df[["A", "B", "C", "D"]].values
x_vals = df["x"].values

# Bin x into classes (tune bins as needed)
bins = [0, 20, 40, 60, 80, 1000]
y_class = np.digitize(x_vals, bins) - 1

# Scale features to [0, pi] for angle encoding
scaler = MinMaxScaler(feature_range=(0, np.pi))
X_scaled = scaler.fit_transform(X)

# Optional: downsample for speed
# idx = np.random.choice(len(X_scaled), size=400, replace=False)
# X_scaled, y_class = X_scaled[idx], y_class[idx]

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_class, test_size=0.2, stratify=y_class, random_state=42
)

print("Train size:", X_train.shape[0], "Test size:", X_test.shape[0])
print("Classes:", np.unique(y_class))

import numpy as np
import matplotlib.pyplot as plt

x_vals = np.array([5, 25, 45, 65, 85, 10, 35, 55, 75, 95])
bins = [0, 20, 40, 60, 80, 1000]

y_class = np.digitize(x_vals, bins) - 1

plt.figure()
plt.scatter(x_vals, y_class)

# Draw horizontal bands
for i in range(len(bins) - 1):
    plt.axhspan(i - 0.5, i + 0.5, alpha=0.1)

plt.xlabel("x values")
plt.ylabel("Bin index (class)")
plt.title("x_vals vs Bin Index with Horizontal Bands")

plt.show()

# -----------------------------
# 2. Define device and circuits
# -----------------------------
n_qubits = 4
n_layers = 4 #3
dev = qml.device("default.qubit", wires=n_qubits)

def feature_map(x):
    for i in range(n_qubits):
        qml.RY(x[i], wires=i)
    for i in range(n_qubits - 1):
        qml.CNOT(wires=[i, i + 1])

def variational_block(weights):
    # weights shape: (n_layers, n_qubits, 3)
    for l in range(n_layers):
        for i in range(n_qubits):
            qml.RX(weights[l, i, 0], wires=i)
            qml.RY(weights[l, i, 1], wires=i)
            qml.RZ(weights[l, i, 2], wires=i)
        for i in range(n_qubits - 1):
            qml.CNOT(wires=[i, i + 1])

@qml.qnode(dev)
def circuit(x, weights):
    feature_map(x)
    variational_block(weights)
    return qml.expval(qml.PauliZ(0))

def model(x, weights):
    # Map expectation value in [-1,1] to logits per class via a simple linear head
    # For simplicity, we treat this as binary-like and then threshold;
    # for multi-class, you’d typically use one-vs-rest or a small classical head.
    return circuit(x, weights)

# -----------------------------
# 3. Loss and training
# -----------------------------
def predict_label(x, weights):
    # Simple thresholding for demonstration:
    # map expval in [-1,1] to 0/1/2/... by binning
    val = model(x, weights)
    # Here we just do binary: <=0 -> 0, >0 -> 1
    # For your multi-class x-bins, you’d usually train one-vs-rest models
    # or design a multi-output head. To keep it simple, we collapse to 2 classes:
    return 1 if val > 0 else 0

# Collapse labels to binary for this demo: class 0 vs others
y_train_bin = (y_train != 0).astype(int)
y_test_bin = (y_test != 0).astype(int)

def loss(weights, X, y):
    preds = [model(x, weights) for x in X]
    # Convert expvals to probabilities via sigmoid-like mapping
    probs = (np.array(preds) + 1) / 2.0  # in [0,1]
    # Binary cross-entropy
    eps = 1e-8
    return -np.mean(y * np.log(probs + eps) + (1 - y) * np.log(1 - probs + eps))

weights_shape = (n_layers, n_qubits, 3)
weights = 0.01 * np.random.randn(*weights_shape)

opt = qml.AdamOptimizer(stepsize=0.05)
n_epochs = 5 #20
batch_size = 32 #32

for epoch in range(n_epochs):
    # mini-batch training
    idx = np.random.permutation(len(X_train))
    X_train_shuffled = X_train[idx]
    y_train_shuffled = y_train_bin[idx]

    for start in range(0, len(X_train_shuffled), batch_size):
        end = start + batch_size
        X_batch = X_train_shuffled[start:end]
        y_batch = y_train_shuffled[start:end]
        weights = opt.step(lambda w: loss(w, X_batch, y_batch), weights)

    train_loss = loss(weights, X_train, y_train_bin)
    print(f"Epoch {epoch+1}/{n_epochs}, loss = {train_loss:.4f}")

# -----------------------------
# 4. Evaluation
# -----------------------------
y_pred_bin = []
y_pred_raw = []   # store raw VQC outputs for regression metrics

for x in X_test:
    val = model(x, weights)
    y_pred_raw.append(val)
    y_pred_bin.append(1 if val > 0 else 0)

y_pred_bin = np.array(y_pred_bin)
y_pred_raw = np.array(y_pred_raw)

# Classification metrics
acc = accuracy_score(y_test_bin, y_pred_bin)
f1_macro = f1_score(y_test_bin, y_pred_bin, average="macro")
f1_weighted = f1_score(y_test_bin, y_pred_bin, average="weighted")

print("\nVQC (binary) accuracy:", acc)
print("F1 macro:", f1_macro)
print("F1 weighted:", f1_weighted)

# ---------------------------------------
# Regression-style metrics on raw outputs
# ---------------------------------------
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test_bin, y_pred_raw)
mse = mean_squared_error(y_test_bin, y_pred_raw)
rmse = np.sqrt(mse)
mape = np.mean(np.abs((y_test_bin - y_pred_raw) / y_test_bin)) * 100
r2 = r2_score(y_test_bin, y_pred_raw)

print("\nRegression-style evaluation on raw VQC outputs:")
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("MAPE:", mape)
print("R²   :", r2)

from sklearn.metrics import roc_auc_score, roc_curve

# ROC–AUC
auc = roc_auc_score(y_test_bin, y_pred_raw)
fpr, tpr, thresholds = roc_curve(y_test_bin, y_pred_raw)

print("\nROC–AUC:", auc)

import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))
plt.plot(fpr, tpr, linewidth=2, label=f"VQC (AUC = {auc:.3f})")
plt.plot([0,1], [0,1], 'k--', label="Random guess")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve – VQC Raw Outputs")
plt.grid(True)
plt.legend()
plt.xlim([0,1])
plt.ylim([0,1])
plt.show()

"""Classical ML algorithms:

> SVM, DT, LR, KNN

"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#Mount Google Drive in Colab
from google.colab import drive
drive.mount('/content/drive')


# Then the path will be:

"/content/drive/My Drive/Datasets_QML/rssiML.csv"

# ---------------------------------------------------------
# 1. Load Dataset
# ---------------------------------------------------------
df = pd.read_csv("/content/drive/My Drive/Datasets_QML/rssiML.csv")

X = df[['A', 'B', 'C', 'D']]
y = df[['x', 'y']]

# ---------------------------------------------------------
# 2. Train/Test Split
# ---------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ---------------------------------------------------------
# 3. Scaling (needed for SVM, kNN, LR)
# ---------------------------------------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ---------------------------------------------------------
# 4. Define Models
# ---------------------------------------------------------
models = {
    "LinearRegression": LinearRegression(),
    "DecisionTree": DecisionTreeRegressor(random_state=42),
    "kNN": KNeighborsRegressor(n_neighbors=5),
    "SVM_RBF": SVR(kernel='rbf', C=100, gamma='scale')
}

# ---------------------------------------------------------
# 5. Train & Evaluate Models
# ---------------------------------------------------------
results = {}

for name, model in models.items():

    # DT does NOT use scaling; others do
    if name == "DecisionTree":
        Xtr, Xte = X_train, X_test
    else:
        Xtr, Xte = X_train_scaled, X_test_scaled

    # Train separate models for x and y
    model_x = model
    model_y = model.__class__(**model.get_params())

    model_x.fit(Xtr, y_train['x'])
    model_y.fit(Xtr, y_train['y'])

    pred_x = model_x.predict(Xte)
    pred_y = model_y.predict(Xte)

    preds = np.vstack([pred_x, pred_y]).T
    true = y_test.values

    mae = mean_absolute_error(true, preds)
    mse = mean_squared_error(true, preds)
    rmse = np.sqrt(mean_squared_error(true, preds))
    r2 = r2_score(true, preds)

    results[name] = {"MAE": mae, "MSE": mse,"RMSE": rmse, "R2": r2}

# ---------------------------------------------------------
# 6. Display Results
# ---------------------------------------------------------
print("\n=== Classical ML Model Performance ===\n")
for model_name, metrics in results.items():
    print(f"{model_name}:")
    print(f"  MAE  = {metrics['MAE']:.4f}")
    print(f"  MSE  = {metrics['MSE']:.4f}")
    print(f"  RMSE = {metrics['RMSE']:.4f}")
    print(f"  R²   = {metrics['R2']:.4f}\n")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score, f1_score

# ---------------------------------------------------------
# 1. Load Dataset
# ---------------------------------------------------------
df = pd.read_csv("/content/drive/My Drive/Datasets_QML/rssiML.csv")

X = df[['A', 'B', 'C', 'D']]
y_class = df['x'].astype(int)   # classification label

# Unique classes (0,5,10,...)
classes = sorted(df['x'].unique())

def to_class(pred):
    """Map continuous prediction to nearest valid class."""
    return min(classes, key=lambda c: abs(c - pred))

# ---------------------------------------------------------
# 2. Train/Test Split
# ---------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y_class, test_size=0.2, random_state=42
)

# ---------------------------------------------------------
# 3. Scaling (needed for SVM, kNN, LR)
# ---------------------------------------------------------
#scaler = StandardScaler()
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ---------------------------------------------------------
# 4. Define Models (regressors)
# ---------------------------------------------------------
models = {
    "LinearRegression": LinearRegression(),
    "DecisionTree": DecisionTreeRegressor(random_state=42),
    "kNN": KNeighborsRegressor(n_neighbors=5),
    "SVM_RBF": SVR(kernel='rbf', C=100, gamma='scale')
}

# ---------------------------------------------------------
# 5. Train & Evaluate Classification Metrics
# ---------------------------------------------------------
results = {}

for name, model in models.items():

    # DT does NOT use scaling
    if name == "DecisionTree":
        Xtr, Xte = X_train, X_test
    else:
        Xtr, Xte = X_train_scaled, X_test_scaled

    clf = model.__class__(**model.get_params())
    clf.fit(Xtr, y_train)

    # Raw continuous predictions
    y_pred_raw = clf.predict(Xte)

    # Convert to nearest class
    y_pred = np.array([to_class(v) for v in y_pred_raw])

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    f1_macro = f1_score(y_test, y_pred, average="macro")
    f1_weighted = f1_score(y_test, y_pred, average="weighted")

    results[name] = {
        "Accuracy": acc,
        "F1_macro": f1_macro,
        "F1_weighted": f1_weighted
    }

# ---------------------------------------------------------
# 6. Display Results
# ---------------------------------------------------------
print("\n=== Classification Metrics (x as class) ===\n")
for model_name, metrics in results.items():
    print(f"{model_name}:")
    print(f"  Accuracy     = {metrics['Accuracy']:.4f}")
    print(f"  F1 (macro)   = {metrics['F1_macro']:.4f}")
    print(f"  F1 (weighted)= {metrics['F1_weighted']:.4f}\n")